from unittest import TestCase

from wxflightpath.zoneFilter import *


class TestZoneFilter(TestCase):
    airport_List = getAirfieldsInFlightPath()
    def test_init(self):
        self.assertEqual(self.airport_List,
                         ['LFPT',
                          'LFRU',
                          'LFXU',
                          'LFPX',
                          'LFPA',
                          'LFPF',
                          'LFPZ',
                          'LFFE',
                          'LFFC',
                          'LFPN',
                          'LFPV',
                          'LFOB',
                          'LFPB',
                          'LFFY',
                          'LFPO',
                          'LFPG',
                          'LFPH',
                          'LFPL',
                          'LFFQ',
                          'LFPP',
                          'LFFL',
                          'LFOX',
                          'LFAR',
                          'LFON',
                          'LFPM',
                          'LFPE',
                          'LFFD',
                          'LFOR',
                          'LFOE',
                          'LFAD',
                          'LFFB',
                          'LFAY',
                          'LFOP',
                          'LFPQ',
                          'LFPK',
                          'LFPU',
                          'LFAI',
                          'LFAQ',
                          'LFAG',
                          'LFOL',
                          'LFPD',
                          'LFAJ',
                          'LFAS',
                          'LFRF',
                          'LFRD',
                          'LFRT',
                          'LFRO',
                          'LFES',
                          'LFRJ',
                          'LFRQ',
                          'LFRB',
                          'LFRL']
                         )

